// CampShare NZ — sample van data
// Photos: Unsplash (free use) — chosen to evoke camper/van interiors & NZ landscape
window.CAMPSHARE_VANS = [
  {
    id: 'kahu',
    name: 'Kahu',
    tagline: 'A reclaimed-rimu retreat for two',
    type: 'Self-contained van',
    region: 'Auckland',
    island: 'north',
    sleeps: 2,
    seats: 2,
    fixedToilet: true,
    pricePerNight: 185,
    rating: 4.96,
    reviews: 47,
    badge: 'Top rated',
    image: 'https://images.unsplash.com/photo-1539183204366-63a0589187ab?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1539183204366-63a0589187ab?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1602002418082-a4443e081dd1?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1626668893632-6f3a4466d109?auto=format&fit=crop&w=900&q=80'
    ],
    tags: ['Off-grid', 'Pet friendly', 'Solar'],
    features: ['Queen bed', 'Diesel heater', 'Solar power 200W', 'Compost toilet', 'Indoor kitchen', 'Outdoor shower', 'Dog welcome', '4WD optional', 'Bluetooth speaker', 'Library shelf'],
    host: { name: 'Marama', initials: 'M', tenure: 'Hosting since 2022', vans: 1 },
    description: 'Built by hand over 14 months from reclaimed rimu and recycled wool insulation, Kahu is a slow-living retreat on wheels. The bed sits under a north-facing skylight, the kitchen has a real chopping board, and there are paperbacks in the cubby above the cab. Perfect for two who like to take their time.'
  },
  {
    id: 'tui',
    name: 'Little Tui',
    tagline: 'Nimble micro-camper for solo road-trippers',
    type: 'Micro camper',
    region: 'Wellington',
    island: 'north',
    sleeps: 2,
    seats: 2,
    fixedToilet: false,
    pricePerNight: 110,
    rating: 4.88,
    reviews: 62,
    badge: 'New',
    image: 'https://images.unsplash.com/photo-1601758174039-2e8eedb3a9d3?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1601758174039-2e8eedb3a9d3?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1533873984035-25970ab07461?auto=format&fit=crop&w=900&q=80'
    ],
    tags: ['Compact', 'Easy drive', 'City friendly'],
    features: ['Double bed', 'Portable toilet', 'Gas cooker', 'Fridge 40L', 'USB power', 'Pop-top roof', 'Awning', 'Auto transmission'],
    host: { name: 'Sam & Olive', initials: 'SO', tenure: 'Hosting since 2024', vans: 2 },
    description: "Little Tui is what we drive when we don't want to think about parking. Manual rooftop pop-up, fold-out double bed, two gas burners and enough room for one bag each. Sized like a car, sleeps like a bach."
  },
  {
    id: 'pounamu',
    name: 'Pounamu',
    tagline: 'Family-sized adventure bus',
    type: 'Camper bus',
    region: 'Christchurch',
    island: 'south',
    sleeps: 5,
    seats: 5,
    fixedToilet: true,
    pricePerNight: 295,
    rating: 4.91,
    reviews: 38,
    badge: 'Family',
    image: 'https://images.unsplash.com/photo-1543395136-281e26ec73fd?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1543395136-281e26ec73fd?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1597083356977-d12fa28af067?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1606768666853-403c90a981ad?auto=format&fit=crop&w=900&q=80'
    ],
    tags: ['Sleeps 5', 'Fixed toilet', 'Shower'],
    features: ['Queen + 2 bunks + dinette bed', 'Indoor shower', 'Fixed toilet', 'Diesel heater', 'Solar 400W', 'Full kitchen', 'Awning', 'Bike rack', 'Children\'s seat'],
    host: { name: 'Te Aroha', initials: 'TA', tenure: 'Hosting since 2021', vans: 1 },
    description: 'Pounamu is our biggest converted bus and the obvious choice when the whole whānau is coming. Bunk beds at the back, queen up front, full wet-room. Built to do the West Coast properly.'
  },
  {
    id: 'haere',
    name: 'Haere',
    tagline: 'Off-grid 4WD ready for gravel roads',
    type: '4WD camper',
    region: 'Queenstown',
    island: 'south',
    sleeps: 2,
    seats: 2,
    fixedToilet: false,
    pricePerNight: 220,
    rating: 4.94,
    reviews: 54,
    image: 'https://images.unsplash.com/photo-1533873984035-25970ab07461?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1533873984035-25970ab07461?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1517824806704-9040b037703b?auto=format&fit=crop&w=900&q=80'
    ],
    tags: ['4WD', 'Off-grid', 'Rooftop tent'],
    features: ['Rooftop tent', 'Diesel cooker', 'Snorkel', '4WD low range', 'Auxiliary fuel', 'Fridge 60L', 'Recovery gear', 'Manual gearbox'],
    host: { name: 'Jared', initials: 'J', tenure: 'Hosting since 2023', vans: 3 },
    description: 'Haere goes where the sealed road ends. A pop-up rooftop tent, full recovery kit, twin batteries and 80 litres of water mean you can disappear for a week without thinking about it. Manual only, sorry.'
  },
  {
    id: 'koru',
    name: 'Koru',
    tagline: 'Vintage Bedford restored with love',
    type: 'Heritage van',
    region: 'Nelson',
    island: 'south',
    sleeps: 4,
    seats: 4,
    fixedToilet: false,
    pricePerNight: 175,
    rating: 4.85,
    reviews: 29,
    badge: 'Heritage',
    image: 'https://images.unsplash.com/photo-1597055181300-e3633a917d09?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1597055181300-e3633a917d09?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1485206412256-701ccc5b93ca?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=900&q=80'
    ],
    tags: ['Vintage', 'Sleeps 4', 'Manual'],
    features: ['Two double beds', 'Gas cooker', '12V fridge', 'Cassette toilet', 'Vinyl record player', 'Awning', 'Outdoor table'],
    host: { name: 'Ngaire', initials: 'N', tenure: 'Hosting since 2020', vans: 1 },
    description: "A 1978 Bedford restored over three years by the family who learned to drive in it. Cream paint, brown stripe, two double beds inside, and a small record player wired into the dash. Don't expect speed; expect to be photographed at every stop."
  },
  {
    id: 'rangi',
    name: 'Rangi',
    tagline: 'High-spec touring van for long trips',
    type: 'Self-contained van',
    region: 'Auckland',
    island: 'north',
    sleeps: 2,
    seats: 2,
    fixedToilet: true,
    pricePerNight: 245,
    rating: 4.98,
    reviews: 81,
    badge: 'Top rated',
    image: 'https://images.unsplash.com/photo-1527786356703-4b100091cd2c?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1527786356703-4b100091cd2c?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1519055548599-6d4d129508c4?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=900&q=80'
    ],
    tags: ['Self-contained', 'Indoor shower', 'Diesel heat'],
    features: ['Queen bed', 'Indoor shower', 'Cassette toilet', 'Induction hob', 'Diesel heater', 'Solar 300W', 'Lithium 200Ah', 'Reversing camera', 'Auto transmission', 'Cruise control'],
    host: { name: 'Hemi', initials: 'H', tenure: 'Hosting since 2022', vans: 2 },
    description: "Rangi is the van we built when we got tired of cold mornings and dead batteries. Lithium house bank, diesel heater, induction hob, full wet room. It's a small apartment that happens to drive."
  },
  {
    id: 'fern',
    name: 'Fern',
    tagline: 'Cosy two-berth with a wood-fire stove',
    type: 'Self-contained van',
    region: 'Dunedin',
    island: 'south',
    sleeps: 2,
    seats: 2,
    fixedToilet: true,
    pricePerNight: 165,
    rating: 4.89,
    reviews: 33,
    image: 'https://images.unsplash.com/photo-1581017093900-5b1d3c1a48bf?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1581017093900-5b1d3c1a48bf?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=900&q=80'
    ],
    tags: ['Wood stove', 'Winter ready', 'Pet friendly'],
    features: ['Double bed', 'Tiny wood stove', 'Compost toilet', 'Gas cooker', 'Fridge 50L', 'Solar 200W', 'Dog welcome'],
    host: { name: 'Lucy', initials: 'L', tenure: 'Hosting since 2023', vans: 1 },
    description: 'Fern has a real little wood stove. In winter it makes the van smell of macrocarpa and the windows steam up while you make porridge. We hand-built every cabinet from native timber off-cuts.'
  },
  {
    id: 'whetu',
    name: 'Whetū',
    tagline: 'Stargazing van with a glass roof',
    type: 'Self-contained van',
    region: 'Coromandel/BOP',
    island: 'north',
    sleeps: 2,
    seats: 2,
    fixedToilet: true,
    pricePerNight: 210,
    rating: 4.92,
    reviews: 41,
    badge: 'Unique',
    image: 'https://images.unsplash.com/photo-1500964757637-c85e8a162699?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1500964757637-c85e8a162699?auto=format&fit=crop&w=1600&q=80',
      'https://images.unsplash.com/photo-1485963631004-f2f00b1d6606?auto=format&fit=crop&w=900&q=80'
    ],
    tags: ['Skylight', 'Self-contained', 'Off-grid'],
    features: ['Queen bed under skylight', 'Cassette toilet', 'Outdoor shower', 'Gas hob', 'Solar 250W', 'Telescope on board', 'Star chart book'],
    host: { name: 'Anika', initials: 'A', tenure: 'Hosting since 2022', vans: 1 },
    description: 'A full-length glass roof over the bed. We added it because we wanted to see stars from the pillow, and now we cannot drive Whetū without people asking about it. Comes with a small telescope.'
  }
];
